### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by Klendat**
This pull request configures this repository to be run on Repl.it.      It adds a `.replit` configuration file and a Repl.it badge to the `README`.
     You can read more about running repos on Repl.it [here](https://docs.repl.it/repls/dot-replit)

### CODE REVIEW

**Comment by amrrs** [comment]
Sorry, just for clarification - @Klendat you're saying that this entire thing could be run on `repl.it` ?

**Comment by Klendat** [comment]
Yes I added a config to run it directly on repl and one click run from the button. Too bad it seems to have been refused.

**Comment by luka1199** [comment]
Hey the pull request got closed because I removed some files from the history. Can you rebase on the new fresh history and submit another pull request? Sorry for the inconvenience 😅

**Comment by Klendat** [comment]
Yeah I can do it tomorrow

**Pull request closed without merging**
